### ISSUE TITLE
Errorr using jurigged on docker

### ISSUE THREAD

**Issue by luhfilho** [breuleux/jurigged#7]
I am getting an error when i am using with docker:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/jurigged", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/jurigged/live.py", line 268, in cli
    run()
  File "/usr/local/lib/python3.9/site-packages/jurigged/live.py", line 188, in run
    runpy.run_path(path, module_object=mod)
  File "/usr/local/lib/python3.9/site-packages/jurigged/runpy.py", line 279, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/usr/local/lib/python3.9/site-packages/jurigged/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/srv/www/s'
```

Dockerfile

```Dockerfile

FROM python:3.9-slim

RUN mkdir /srv/www/

ADD ./ /srv/www/

WORKDIR /srv/www/

ENV GRPC_PYTHON_VERSION 1.39.0
RUN python -m pip install --upgrade pip
RUN pip install grpcio==${GRPC_PYTHON_VERSION} grpcio-tools==${GRPC_PYTHON_VERSION} grpcio-reflection==${GRPC_PYTHON_VERSION} grpcio-health-checking==${GRPC_PYTHON_VERSION} grpcio-testing==${GRPC_PYTHON_VERSION}

RUN pip install -r requirements.txt

RUN pip install jurigged
ENTRYPOINT ["jurigged"]
CMD ["main.py"]

```

Python file main.py
```python
import time
import datetime

def main():
    while True:
        print("Executed %s" % datetime.datetime.now())
        time.sleep(5)


main()

```

**Comment by breuleux** [comment]
I built the container and I was able to run it without any issues, so I don't know.

I'll need more information. What OS/distro are you using, what commands did you use to build and run the image? Does it work using `python -m jurigged main.py`, or with `import jurigged; jurigged.watch()`?
