### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 594: illegal multibyte sequence

### ISSUE THREAD

**Issue by InPRTx** [breuleux/jurigged#8]
```
Traceback (most recent call last):
  File "C:\Users\InPRTx\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\InPRTx\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\InPRTx\AppData\Local\Programs\Python\Python38\lib\site-packages\jurigged\__main__.py", line 4, in <module>
    cli()
  File "C:\Users\InPRTx\AppData\Local\Programs\Python\Python38\lib\site-packages\jurigged\live.py", line 258, in cli
    mod, run = find_runner(opts, pattern)
  File "C:\Users\InPRTx\AppData\Local\Programs\Python\Python38\lib\site-packages\jurigged\live.py", line 183, in find_runner
    registry.prepare("__main__", path)
  File "C:\Users\InPRTx\AppData\Local\Programs\Python\Python38\lib\site-packages\jurigged\register.py", line 60, in prepare
    f.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 594: illegal multibyte sequence
```
jurigged 0.3.3

It seems that it is not set to open the file with utf8 encoding by default

https://github.com/breuleux/jurigged/blob/75dc1a599a8c6c2807cb114e66f9b59f986b8913/jurigged/register.py#L57

**Comment by InPRTx** [comment]
```
Traceback (most recent call last):
  File "c:\users\inprtx\appdata\local\programs\python\python38\lib\site-packages\jurigged\live.py", line 101, in refresh
    cf.refresh()
  File "c:\users\inprtx\appdata\local\programs\python\python38\lib\site-packages\jurigged\codetools.py", line 1119, in refresh      
    new_source = self.read_source()
  File "c:\users\inprtx\appdata\local\programs\python\python38\lib\site-packages\jurigged\codetools.py", line 1066, in read_source  
    source = open(self.filename).read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 583: illegal multibyte sequence
```

https://github.com/breuleux/jurigged/blob/54b49a50a7615a6bc93df386bf06961ea14f5c3e/jurigged/codetools.py#L1033

Maybe you should add encoding='utf-8' to all open(*,'r')

**Comment by breuleux** [comment]
Ah, I guess this was a lazy fix on my part 😅
